generate-go:
	antlr -o go -Dlanguage=Go -visitor qasm3Lexer.g4 qasm3Parser.g4

generate-python2:
	antlr -o python -Dlanguage=Python2 -visitor qasm3Lexer.g4 qasm3Parser.g4

generate-python3:
	antlr -o python -Dlanguage=Python3 -visitor qasm3Lexer.g4 qasm3Parser.g4

generate-java:
	antlr -o java -Dlanguage=Java -visitor qasm3Lexer.g4 qasm3Parser.g4

generate-cpp:
	antlr -o cpp -Dlanguage=Cpp -visitor qasm3Lexer.g4 qasm3Parser.g4

generate-js:
	antlr -o js -Dlanguage=JavaScript -visitor qasm3Lexer.g4 qasm3Parser.g4
